// Create a new video
POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "New Video",
  "description": "This is a other new video description.",
  "duration": 120
}

###

// List all videos data, including UUIDs
GET http://localhost:3333/videos

###

// Get a specific video by UUID
PUT http://localhost:3333/videos/video-uuid
Content-Type: application/json

{
  "title": "Updated Video Title",
  "description": "This is an updated video description.",
  "duration": 150
}

###

// Delete a specific video by UUID
DELETE http://localhost:3333/videos/video-uuid
