// Create a new video
POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "New Video Title",
  "description": "This is a new video description.",
  "duration": 120
}

###

// List all videos data
GET http://localhost:3333/videos

###

// Filter videos by search term
GET http://localhost:3333/videos?search=search-term

###

// Get a specific video by UUID
PUT http://localhost:3333/videos/video-uuid
Content-Type: application/json

{
  "title": "Updated New Video Title",
  "description": "This is an updated video description.",
  "duration": 150
}

###

// Delete a specific video by UUID
DELETE http://localhost:3333/videos/video-uuid
